server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: authservice

jwt:
  token:
    secret-key: BW6TsEkliu
    issuer: AuthService
    expire-in-minutes: 15

downstream:
  userservice:
    search-user: http://userservice/users/search?username=%s